### PR TITLE
Add missing {% endif %}

### PR DESCRIPTION
**Pull request by bjnortier**
The ```tags``` line is missing an ```endif```

### CODE REVIEW

**Comment by Wolfr** [comment]
Not having this leads to #6 . Thanks for the fix!

**Comment by bjnortier** [comment]
Pleasure

**Comment by funkaoshi** [comment]
+1

**Review by vallieres — APPROVED** [review]

**Comment by vallieres** [comment]
Sorry about the huge delay, I did not realize I had opened pull requests 🤦‍♂️

**Pull request merged**
