### PR TITLE
5 Points addressed: Missing endif tag + Extra double quotes in JSON + need to jsonify + Author can be Object + typo in Added a 5th commit, just noticed typo in enclosure_length

### PR DESCRIPTION
**Pull request by wkhayrattee**
This PR address the following:
- Missing endif
- You should jsonify the output for image, else end up with "key" => "value" instead of "key":"value"
- No need for enclosing double quotes as IMAGE is an OBJECT, should be enclosed within curly braces instead.

### CODE REVIEW

**Comment by wkhayrattee** [comment]
I have added a 4th commit to this to address: author (both at channel & item level) can be an object as per jsonfeed specs: https://jsonfeed.org/version/1

**Comment by wkhayrattee** [comment]
Added a 5th commit, just noticed typo in enclosure_length

**Comment by vallieres** [comment]
LGTM!

**Comment by wkhayrattee** [comment]
awesome, thanks @vallieres !
Keep up the good work with all the Jekyllrb Spirit!
cheers

**Pull request merged**
